//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JNMTaskManagement_Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApiCallLog
    {
        public long Id { get; set; }
        public string APIName { get; set; }
        public long ReferenceId { get; set; }
        public string TableName { get; set; }
        public string ApiURL { get; set; }
        public string ApiResponse { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
    }
}
