//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JNMTaskManagement_Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TaskDetail()
        {
            this.TaskPokeDetails = new HashSet<TaskPokeDetail>();
        }
    
        public long TaskId { get; set; }
        public string Title { get; set; }
        public int PriorityId { get; set; }
        public string Description { get; set; }
        public string Client { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<int> DIvisionId { get; set; }
        public string Profile { get; set; }
        public string KRA { get; set; }
        public string ReminderDetails { get; set; }
        public string Holiday { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Time { get; set; }
        public int FrequencyId { get; set; }
        public Nullable<int> AlertId { get; set; }
        public Nullable<int> AlertId1 { get; set; }
        public Nullable<int> AlertId2 { get; set; }
        public string Assign { get; set; }
        public bool IsReportingField { get; set; }
        public string Element { get; set; }
        public Nullable<int> NumericF1 { get; set; }
        public Nullable<int> NumericF2 { get; set; }
        public Nullable<int> NumericF3 { get; set; }
        public Nullable<int> NumericF4 { get; set; }
        public string AttachmentFileName { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public long CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<long> DeletedBy { get; set; }
    
        public virtual FrequencyTypeMaster FrequencyTypeMaster { get; set; }
        public virtual PriorityMaster PriorityMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaskPokeDetail> TaskPokeDetails { get; set; }
    }
}
